apiVersion: v1
kind: Service
metadata:
  name: upload-service
  labels:
    app: upload-app
spec:
  selector:
    app: upload-app
  ports:
    - name: http
      port: 4001
      targetPort: 4001
  type: LoadBalancer
