# Generated by Django 6.0 on 2025-12-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                ("id", models.CharField(primary_key=True, serialize=False)),
                ("user_email", models.CharField(max_length=256)),
                ("file_key", models.CharField(max_length=512)),
                ("data", models.JSONField()),
                ("timestamp", models.DateTimeField()),
                ("sources_links", models.JSONField(default=list)),
            ],
            options={
                "db_table": "chathistory",
                "managed": False,
            },
        ),
    ]
